company_configs = {
    "SBER1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "SBER5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"GAZP1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "GAZP5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"LKOH1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "LKOH5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"VTBR1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "VTBR5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"PLZL1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "PLZL5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"YNDX1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "YNDX5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"SNGS1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "SNGS5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"GMKN1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "GMKN5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"ROSN1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "ROSN5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"TRNFP1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "TRNFP5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"NVTK1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "NVTK5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"TATN1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "TATN5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"ALRS1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "ALRS5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"MTLR1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "MTLR5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"TCSG1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "TCSG5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
"POLY1": {
        'horizon': 1,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    "POLY5": {
        'horizon': 5,
        "history": 5,
        "step": 1,
        "from_last": True,
        "test_last": True,
        "lag_features": 10,
        "lag_time_features": 10,
        "diff_features": [1, 2, 3, 4, 5, 6, 7, 14, 30, 100, 150, 300],
        'trend': True,
        'train_on_trend': False,
        'trend_type': 'decompose',  # one of 'decompose', 'decompose_STL', 'linear' or 'rolling'
        'trend_size': 3,
        'decompose_period': 15,
        'detect_step_quantile': 0.01,
        'detect_step_window': 1,
        'detect_step_threshold': 0.7,
        'rolling_size': 1
        },
    }
