version: "3.8"

services:
  postgres:
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
  frontend:
    build: ./frontend
    ports:
      - 80:3000
    restart: always
    init: true

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres


volumes:
  postgres_data:
