CREATE SCHEMA IF NOT EXISTS content;

CREATE TABLE IF NOT EXISTS content.tickers (
    id UUID PRIMARY KEY,
    secid TEXT NOT NULL,
    boardid TEXT NOT NULL,
    shortname TEXT,
    prevprice FLOAT,
    lotsize BIGINT,
    facevalue FLOAT,
    status TEXT,
    boardname TEXT,
    decimials INT,
    secname TEXT,
    remarks TEXT,
    marketcode TEXT,
    instrid TEXT,
    sectorid TEXT,
    minstep FLOAT,
    prevwaprice FLOAT,
    faceunit TEXT,
    prevdate TIMESTAMP WITH TIME ZONE,
    issuesize BIGINT,
    isin TEXT,
    latname TEXT,
    regnumber TEXT,
    prevlegalcloseprice FLOAT,
    currencyid TEXT,
    sectype TEXT,
    listlevel INT,
    settledate TIMESTAMP WITH TIME ZONE, 
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);
