# Generated by Django 5.0 on 2023-12-07 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0005_alter_stock_prevdate_alter_stock_settledate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='created',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='stock',
            name='PREVDATE',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 21, 0, 24, 985970)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='SETTLEDATE',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 21, 0, 24, 986189)),
        ),
    ]
