# Generated by Django 5.0 on 2023-12-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0006_remove_stock_created_remove_stock_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='PREVDATE',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='SETTLEDATE',
            field=models.DateField(blank=True),
        ),
    ]
