"""add metric models

Revision ID: 2fa425b1b3e9
Revises: 1bcca22b5d1a
Create Date: 2023-12-09 18:07:49.261649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa425b1b3e9'
down_revision: Union[str, None] = '1bcca22b5d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tisker_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('delta', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['tisker_id'], ['tiskers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tisker_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    # ### end Alembic commands ###
